---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "SEInfraConfig - 1st International Workshop on Software Engineering for Infrastructure and Configuration Code"
keywords:    "Workshop, Configuration"
description: ""
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "" ## put YOUR key here to enable tracking! (blank to disable)
source_link: "http://github.com/seinfraconfig/seinfraconfig.github.io"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#bfd7ff'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#ffcc75'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

future: true

orga-mail: mark.santolucito@yale.edu

plugins:
    - jekyll-redirect-from

theme: jekyll-theme-minimal